### ISSUE TITLE
Please consider changing the logo image

### ISSUE THREAD

**Issue by DonMcNamara** [emanuele-em/man-in-the-middle-proxy#12]
Please consider changing the logo.

https://en.wikipedia.org/wiki/Native_American_mascot_controversy

**Comment by emanuele-em** [comment]
yes a lot of people say me that it could be ambiguous, thank you

**Comment by DonMcNamara** [comment]
It is a very complex issue. Thank you for considering it.

**Comment by emanuele-em** [comment]
@DonMcNamara the most complex considering that it is the third time someone report the logo for someone who has taken offence here and there
