### ISSUE TITLE
Allow proxying for other devices in the same network

### ISSUE THREAD

**Issue by yuankunzhang** [emanuele-em/man-in-the-middle-proxy#17]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The proxy listens on 127.0.0.1, which only allows connections from localhost. I want to use the proxy for other devices in the network.

**Comment by emanuele-em** [comment]
Sure, it is the first things to do, I want to add a setting panel on startup where you can write the listen address, for now you can go to mitm_proxy/main.rs and change the address from 127.0.0.1 to 192.168._._
remember to trust the generated certificate also on the other devices

**Comment by th7nder** [comment]
Hey! I'd like to help you with this one.

**Comment by emanuele-em** [comment]
> Hey! I'd like to help you with this one.

No problem!

**Comment by th7nder** [comment]
I've been going through the code and came up with an initial idea for the solution.
How about we don't start the proxy automatically, but add the panel you mentioned it in the main window and start it only at the request of a user?

![image](https://user-images.githubusercontent.com/8305170/220747888-665ba2b2-e58c-4a9e-add9-617107d868d7.png)
Something like that, but styled of course.

**Comment by emanuele-em** [comment]
the shown solution is not bad but why you show also the bottom parts like the table or the control buttons if the listening isn't started yet? Maybe is only a cited "style" problem, in this case it's ok!

**Comment by th7nder** [comment]
Ok, I got some dirty prototype working, that's the screenshot of it. 
I'll hide it when it's not started and make it look beter haha.

Bonus question:
Should we should clear the requests automatically after we stopped proxy/started on a new port?

**Comment by emanuele-em** [comment]
> Ok, I got some dirty prototype working, that's the screenshot of it. 
> I'll hide it when it's not started and make it look beter haha.
> 
> Bonus question:
> Should we should clear the requests automatically after we stopped proxy/started on a new port?

Yes, to avoid mistakes this is a good solution, in future I'll implement a "preserve log" button

**Comment by th7nder** [comment]
That's great news, I see that PR has been merged.
Should we close the issue or there is something more needed to be done?
