### ISSUE TITLE
Usability Upgrade - Communication between GUI and API with type consistency

### ISSUE THREAD

**Issue by emanuele-em** [emanuele-em/man-in-the-middle-proxy#20]
Due to me and my initial laziness all communications between API and eGUI are done trough String in the following way:
_1._ Api `Structs` types **->** _2._ Convert all fields to `String` (even in twisted ways) **->** _3._ `Output Struct` (of `String`) **->** _4._ Send `Output Struct` via Thread channel to eGUI **->** _5_. eGui Receives `Output Struct` **->** _6._ eGui convert it to a new `Requests struct` (of `String`) in order to print it correctly.

_**It Sucks.**_

The goal is to avoid string conversion and if possible make order and consistency between API types and eGUI types in this way:
_1._ API Structs types **->** _2._ send that type via Channel **->** _3._ eGui Receives the structs and print it directly

**Comment by emanuele-em** [comment]
@MMukundi

**Comment by MMukundi** [comment]
I'll take on this one! I'm thinking the best path here is probably to embed the http response and requests largely as-is:
<img width="1176" alt="Screenshot 2023-02-21 at 12 59 09 PM" src="https://user-images.githubusercontent.com/45983298/220451507-e130339b-f595-4e91-b473-5b1dadbc2d59.png">
<img width="1161" alt="Screenshot 2023-02-21 at 1 00 32 PM" src="https://user-images.githubusercontent.com/45983298/220451504-e3fd5b2b-ebad-43bf-9b8f-634e8f9f3358.png">

The `body
