### ISSUE TITLE
Tauri-yew Migration

### ISSUE THREAD

**Issue by emanuele-em** [emanuele-em/man-in-the-middle-proxy#47]
@sak96 please use [tauri-yew-migration branch](https://github.com/emanuele-em/man-in-the-middle-proxy/tree/tauri-yew-migration)

**Comment by sak96** [comment]
#9 might be fixed with this.

**Comment by sak96** [comment]
@emanuele-em  i think almost all features are done after merging #53. let me know if something is missing.

- Some Refactoring might be required for correct placement of components.
- Some of the clone of request can be avoided completely by using ` std::rc::Rc` as they are not mutated only borrowed not mutated
- Add yewdux or other library to store state in local storage.
- Add yew_router to have separate pages for separate views. 


The instruction to run app is mentioned [here](https://github.com/emanuele-em/man-in-the-middle-proxy/blob/tauri-yew-migration/tauri-ui/CONTRIBUTING.md)

**Comment by emanuele-em** [comment]
yes thank you for your awesome work, today I proceed with some refactor on tauri-ui branch and for minor fixes, good job @sak96

**Comment by sak96** [comment]
i see i missed mentioning trunk :( in contrib.md

**Comment by sak96** [comment]
The UI now looks very good.
awesome stuff: @emanuele-em 

I see you are trying to fix rust.yml
may be you can use for releasing binaries

https://github.com/actions/create-release

**Comment by sak96** [comment]
can you run
```bash
rustup update
```
That will update clippy to latest version.
