### ISSUE TITLE
Delete single request

### ISSUE THREAD

**Issue by emanuele-em** [emanuele-em/man-in-the-middle-proxy#8]
A small button that allow you to remove a single request and relative response from the list

**Comment by phillyphil91** [comment]
Hi @emanuele-em I would like to work on this

**Comment by emanuele-em** [comment]
@phillyphil91 thank you! :)

**Comment by emanuele-em** [comment]
@phillyphil91 do you want some help? Feel free to ask in that case!

**Comment by phillyphil91** [comment]
thanks @emanuele-em 
I'm currently struggling with setting up the CA and run the current version locally. But I think this something that I need to solve on my own.

**Comment by emanuele-em** [comment]
ok no problem! remember to install [openssl](https://www.openssl.org/) on your device

**Comment by phillyphil91** [comment]
hi @emanuele-em got everything to work now.

Are you thinking of having the button to delete a request on each request line, for example next to the magnifying glass or rather a field in the top panel where one could specify the ID of a request and then delete that one. 

The second approach of course would me that there needs to something to uniquely identify the request.

Also I think a bit of reformatting could be done in general. `cargo fmt` and `cargo clippy` changed the code a bit. But maybe that's something to do for a different PR.

**Comment by emanuele-em** [comment]
Awesome! Thank you for your work! Best solution is to add a small "x" for each request, this solution allow users to delete useless requests quickly
